version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci(github-actions): "
    labels:
      - "build"
      - "dependencies"
      - "github_actions"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    labels:
      - "build"
      - "dependencies"
      - "docker"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"
