run:
  modules-download-mode: readonly
  allow-parallel-runners: true

# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - depguard # unnecessary
    - dupl # too many unnecessary detections
    - exhaustruct # https://github.com/GaijinEntertainment/go-exhaustruct
    - gci # unnecessary
    - goconst # unnecessary
    - godox # unnecessary
    - gomnd # deprecated https://github.com/tommy-muehle/go-mnd
    - interfacebloat # unnecessary
    - lll # unnecessary
    - nlreturn # ignore "return with no blank line before"
    - nolintlint # unnecessary
    - nonamedreturns # unnecessary
    - varnamelen # unnecessary
    - wsl # ignore "declarations should never be cuddled"

linters-settings:
  godot:
    period: false
  goimports:
    local-prefixes: "github.com/kunitsucom/arcgen"
  wrapcheck:
    ignoreSigs:
      - func errors.New(text string) error
      - func fmt.Errorf(format string, a ...any) error
      - func fmt.Errorf(format string, a ...interface{}) error
      - func github.com/kunitsucom/util.go/errors.Errorf(format string, a ...interface{}) error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - cyclop
        - dupl
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - gocyclo
        - goerr113
        - gosec
        - ireturn
        - maintidx
        - noctx
        - revive
        - testpackage
        - varnamelen
        - wrapcheck
